Enhancement/edc refactoring (#3)
* fix linting & type checking, unit tests failing

* added uv to docker build chain

* updated workflow

* fix: assertEqual instead of assertEquals

* fix pipeline

* fixed test_user

* fixed pipeline fr this time

* new entrypoint for github action containers

* changed github action image

* fixed uv command in github actions

* changed github actions to use uv action

* uv sync with optional dependencies

* fixed ./dev to use uv fully

* fixed licensecheck

* fixed dev test

* reuse fix

* update actions and pre-commit dependencies

* undo Docker changes to fix build

* update SPDX-FileCopyrightText header

* improved shellcheck

* update docstrings doc generation

* simplify dev install

* pin markdownlint version and add global license

* fix deps

* refactoring next part

* ci ci env var error

* fix missing license file

* update dependabot for security only

---------

Co-authored-by: HeinrichAD <HeinrichAD@users.noreply.github.com>

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,10 +1,8 @@
 #!/bin/bash
-
-# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
-# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
 #
+# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
 # SPDX-License-Identifier: Apache-2.0
-
+#
 ###############################################################################
 # Helper commands #
 ###################
@@ -95,8 +93,11 @@ function version() {
 
 function versions() {
   info "versions"
-  info "$(python --version)"
-  info "$(python -m pip --version)"
+  if ! command -v docker > /dev/null 2>&1; then
+    warn "uv not found, skipping uv version"
+  else
+    info "uv version: $(uv --version)"
+  fi
   if ! command -v docker > /dev/null 2>&1; then
     warn "docker not found, skipping docker version"
   else
@@ -109,31 +110,16 @@ function versions() {
 
 function install() {
   versions
-  info "install package"
-  if [ "$#" -eq "0" ]; then
-    python -m pip install -e .
-  else
-    python -m pip install "$@"
-
-    # check if "doc" extra should be installed
-    install_doc=false
-    for value in "$@"; do
-      value="${value//[[:blank:]]/}"
-      [[ "$value" =~ \[(.*,)?(doc|all)(,.*)?\] ]] && install_doc=true
-    done
-    if [[ "$install_doc" == "true" ]]; then
-      info "install markdown linter"
-      if command -v npm > /dev/null 2>&1; then
-        npm install --no-save markdownlint-cli2
-      else
-        warn "npm not found, skipping markdownlint-cli2 installation"
-      fi
+  if ! command -v uv &> /dev/null; then
+    if ! command -v curl &> /dev/null; then
+      error "uv and curl are not installed. Please install one of them."
+      exit 1
     fi
+    info "install uv"
+    curl -LsSf https://astral.sh/uv/install.sh | sh
   fi
-  #info "post-install"
-  #py_pack_dir="$(python -c 'import site; print(site.getsitepackages()[0])')"
-  #info " + setup user documentation plugins"
-  #cp "$py_pack_dir/plantuml_markdown.py" "$py_pack_dir/markdown/extensions/"
+  info "install package"
+  uv sync --all-extras
 }
 
 function clean() {
@@ -155,31 +141,31 @@ function clean() {
 function start() {
   docker compose up -d db redis
   migrate
-  python manage.py runserver
+  uv run python manage.py runserver
 }
 
 function celery() {
   docker compose up -d redis
   DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-"fl_server.settings.development"}" \
-    python -m celery --workdir "${PROJECT_ROOT_ABSOLUTE}" --app fl_server_ai worker --loglevel=INFO
+    uv run celery --workdir "${PROJECT_ROOT_ABSOLUTE}" --app fl_server_ai worker --loglevel=INFO
 }
 
 function migrate() {
-  python manage.py migrate
-  python manage.py check
+  uv run python manage.py migrate
+  uv run python manage.py check
 }
 
 function makemigrations() {
-  python manage.py makemigrations fl_server_core
+  uv run python manage.py makemigrations fl_server_core
 }
 
 function manage() {
-  python manage.py "$@"
+  uv run python manage.py "$@"
 }
 
 function superuser() {
 	DJANGO_SUPERUSER_PASSWORD="${DJANGO_SUPERUSER_PASSWORD:-"password"}" \
-    python manage.py createsuperuser --username admin --email "admin@example.com" --no-input
+    uv run python manage.py createsuperuser --username admin --email "admin@example.com" --no-input
 }
 
 function collectstatic() {
@@ -189,7 +175,7 @@ function collectstatic() {
   rm -rf static
   rm -rf "${BUILD_ROOT}/static"
   FL_DJANGO_SECRET_KEY="${FL_DJANGO_SECRET_KEY:-}" FL_POSTGRES_PASSWD="${FL_POSTGRES_PASSWD:-}" \
-    python manage.py collectstatic --settings "fl_server.settings.production"
+    uv run python manage.py collectstatic --settings "fl_server.settings.production"
   info "compressing static files"
   mkdir -p "${BUILD_ROOT}/static"
   info "  | create admin.tar.gz"
@@ -234,7 +220,7 @@ function test() {
   coverage-report
   if [ "${HTTP_SERVE}" = "true" ]; then
     if [ -d "${BUILD_ROOT}/htmlcov" ]; then
-      python -m http.server --directory "${BUILD_ROOT}/htmlcov" 8080
+      uv run -m http.server --directory "${BUILD_ROOT}/htmlcov" 8080
     else
       error "no coverage report found"
       exit 1
@@ -252,55 +238,56 @@ function lint() {
 
 function lint-code() {
   info "lint code"
-  info "flake8 version: $(python -m flake8 --version | xargs)"
-  python -m flake8 "${SOURCE_CORE}"
-  python -m flake8 "${SOURCE_API}"
-  python -m flake8 "${SOURCE_AI}"
-  python -m flake8 "${SOURCE_DJANGO}"
-  python -m flake8 "${SCRIPTS_ROOT}"
+  info "flake8 version: $(uv run flake8 --version | xargs)"
+  uv run flake8 "${SOURCE_CORE}"
+  uv run flake8 "${SOURCE_API}"
+  uv run flake8 "${SOURCE_AI}"
+  uv run flake8 "${SOURCE_DJANGO}"
+  uv run flake8 "${SCRIPTS_ROOT}"
 }
 
 function lint-doc() {
   info "lint documentation"
   # use markdownlint from David Anson (based on nodejs)
   # https://github.com/DavidAnson/markdownlint
-  npm exec markdownlint-cli2 "${DOC_ROOT}/**/*.md" "${PROJECT_ROOT}/README.md"
+  npm exec "markdownlint-cli2@0.22.0" -- "${DOC_ROOT}/**/*.md" "${PROJECT_ROOT}/README.md"
 }
 
 function lint-scripts() {
   info "lint bash scripts"
-  info "shellcheck $(shellcheck --version | head -n 2 | tail -n 1)"
-  shellcheck --external-sources --shell bash --source-path "${PROJECT_ROOT}" "${PROJECT_ROOT}/dev"
-  shellcheck --external-sources --shell bash --source-path "${SCRIPTS_ROOT}" "${SCRIPTS_ROOT}/"*.sh
+  info "shellcheck $(uv run shellcheck --version | head -n 2 | tail -n 1)"
+  uv run shellcheck --external-sources --shell bash --source-path "${PROJECT_ROOT}" "${PROJECT_ROOT}/dev"
+  uv run shellcheck --external-sources --shell bash --source-path "${SCRIPTS_ROOT}" "${SCRIPTS_ROOT}/"*.sh
 }
 
 function mypy() {
   info "type checking"
-  python -m mypy "${SOURCE_CORE}"
-  python -m mypy "${SOURCE_API}"
-  python -m mypy "${SOURCE_AI}"
-  python -m mypy "${SOURCE_DJANGO}"
+  uv run mypy "${SOURCE_CORE}"
+  uv run mypy "${SOURCE_API}"
+  uv run mypy "${SOURCE_AI}"
+  uv run mypy "${SOURCE_DJANGO}"
   if find "${SCRIPTS_ROOT}" -type f -name "*.py" | grep -q .; then
-    python -m mypy "${SCRIPTS_ROOT}"
+    uv run mypy "${SCRIPTS_ROOT}"
   fi
 }
 
 function coverage() {
   info "run python tests with coverage"
-  python -m coverage run manage.py test
-  python -m coverage html --directory "${BUILD_ROOT}/htmlcov"
+  # TODO should we start the DB here (docker compose up db -d) or better not?
+  uv run coverage run manage.py test
+  uv run coverage html --directory "${BUILD_ROOT}/htmlcov"
 }
 
 function coverage-report() {
   info "print test coverage report"
-  python -m coverage report
+  uv run coverage report
 }
 
 function doc() {
   versions
   info
-  mkdocs_version="$(python -m mkdocs --version)"
-  info "${mkdocs_version#"python -m "}"
+  mkdocs_version="$(uv run mkdocs --version)"
+  info "${mkdocs_version#"uv run "}"
   # check if the user has passed the --dirtyreload flag
   dirty_flag=false
   for value in "$@"; do
@@ -314,34 +301,30 @@ function doc() {
   # create and serve documentation
   DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-"fl_server.settings.production"}" \
     FL_DJANGO_SECRET_KEY="${FL_DJANGO_SECRET_KEY:-}" FL_POSTGRES_PASSWD="${FL_POSTGRES_PASSWD:-}" \
-    python -m mkdocs serve "$@"
+    uv run mkdocs serve "$@"
 }
 
 function doc-build() {
   versions
-  mkdocs_version="$(python -m mkdocs --version)"
-  info "${mkdocs_version#"python -m "}"
+  mkdocs_version="$(uv run mkdocs --version)"
+  info "${mkdocs_version#"uv run "}"
   info "build documentation"
   DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-"fl_server.settings.production"}" \
     FL_DJANGO_SECRET_KEY="${FL_DJANGO_SECRET_KEY:-}" FL_POSTGRES_PASSWD="${FL_POSTGRES_PASSWD:-}" \
-    python -m mkdocs build "$@"
+    uv run mkdocs build "$@"
 }
 
 function licenses() {
   info "search for license conflicts"
-  licensecheck
+  uv run licensecheck
   info "search for non-compliant files with REUSE"
-  python -m reuse lint
+  uv run reuse lint
 }
 
 function safety-check() {
   info "check dependencies for known security vulnerabilities"
   # main only no dev dependencies etc.
-  python -m tox --recreate -e safety
-  # alternative
-  #python -m pip install -U safety
-  #safety check
-  ##python -m pip uninstall safety
+  uv run tox --recreate -e safety
 }
 
 
